import fs from 'node:fs';
import path from 'node:path';

import { format } from 'prettier';

import { getDeploymentAddresses } from './deployment-addresses.js';

const PRETTIER_CONFIG = path.join(import.meta.dirname, '..', '..', '.prettierrc');
const DATA_DIR = path.join(import.meta.dirname, '..', '..', 'data');
const OUTPUT_DIR = path.join(import.meta.dirname, '..', '..', 'src', 'generated');

// src/ imports this data, and the published package has to serve both an `import` and a `require`.
// A JSON import needs an import attribute under ES modules and rejects one under CommonJS, so no
// single source file satisfies both. Emitting TypeScript sidesteps the question.
const header = (generatedBy: string) => `// ===========================================================================
// DO NOT EDIT THIS FILE MANUALLY!
//
// The contents have been added automatically.
// See: ${generatedBy} for more information
// ===========================================================================
`;

// Deliberately no \`as const\`: a JSON import widens its values, and narrowing them here would
// change the public type surface of the package.
function declaration(name: string, value: string) {
  return `export const ${name} = ${value};\n`;
}

async function formatContent(content: string) {
  const prettierConfig = JSON.parse(fs.readFileSync(PRETTIER_CONFIG, 'utf8'));
  return format(content, { ...prettierConfig, parser: 'typescript' });
}

export async function getMetadataModule(): Promise<string> {
  const read = (fileName: string) => fs.readFileSync(path.join(DATA_DIR, fileName), 'utf8');
  const content = [
    header('scripts/generate-metadata.ts'),
    declaration('auctioneerMetadata', read('auctioneer-metadata.json')),
    declaration('dapiManagementMetadata', read('dapi-management-metadata.json')),
  ].join('\n');
  return formatContent(content);
}

export async function getDeploymentAddressesModule(): Promise<string> {
  const content = [
    header('scripts/generate-deployment-addresses.ts'),
    declaration('deploymentAddresses', getDeploymentAddresses()),
  ].join('\n');
  return formatContent(content);
}

export const METADATA_FILE = path.join(OUTPUT_DIR, 'metadata.ts');
export const DEPLOYMENT_ADDRESSES_FILE = path.join(OUTPUT_DIR, 'deployment-addresses.ts');
