import type { GoAsyncOptions } from '@api3/promise-utils';

export const goAsyncOptions: GoAsyncOptions = {
  retries: 5,
  attemptTimeoutMs: 10_000,
  totalTimeoutMs: 50_000,
  delay: {
    type: 'random',
    minDelayMs: 2000,
    maxDelayMs: 5000,
  },
};

export const skippedChainAliasesInOevAuctionHouseNativeCurrencyRateValidation = [];

export const skippedChainAliasesInOwnableCallForwarderConstructorArgumentVerification = [
  'apechain',
  'apechain-arbitrum-sepolia-testnet',
  'arbitrum',
  'arbitrum-sepolia-testnet',
  'atleta-testnet',
  'avalanche',
  'avalanche-testnet',
  'base',
  'base-sepolia-testnet',
  'berachain',
  'berachain-testnet',
  'bitlayer',
  'bitlayer-testnet',
  'blast',
  'blast-sepolia-testnet',
  'bob',
  'bob-sepolia-testnet',
  'bsc',
  'bsc-testnet',
  'core',
  'core-testnet',
  'ethereum',
  'ethereum-holesky-testnet',
  'ethereum-sepolia-testnet',
  'fraxtal',
  'fraxtal-holesky-testnet',
  'gnosis',
  'gnosis-testnet',
  'inevm',
  'inevm-testnet',
  'ink',
  'ink-sepolia-testnet',
  'kava',
  'kava-testnet',
  'kroma',
  'kroma-sepolia-testnet',
  'lightlink',
  'lightlink-sepolia-testnet',
  'linea',
  'linea-sepolia-testnet',
  'lumia',
  'lumia-sepolia-testnet',
  'manta',
  'manta-sepolia-testnet',
  'mantle',
  'mantle-sepolia-testnet',
  'megaeth-testnet',
  'merlin',
  'merlin-testnet',
  'metal',
  'metis',
  'metis-sepolia-testnet',
  'mode',
  'mode-sepolia-testnet',
  'monad-testnet',
  'moonbeam',
  'moonbeam-testnet',
  'moonriver',
  'odyssey-sepolia-testnet',
  'oev-network',
  'opbnb',
  'opbnb-testnet',
  'optimism',
  'optimism-sepolia-testnet',
  'polygon',
  'polygon-sepolia-testnet',
  'polygon-zkevm',
  'polygon-zkevm-sepolia-testnet',
  'rari',
  'rari-arbitrum-sepolia-testnet',
  'rechain-testnet',
  'ronin',
  'ronin-testnet',
  'scroll',
  'scroll-sepolia-testnet',
  'sei',
  'sei-testnet',
  'soneium',
  'soneium-sepolia-testnet',
  'sonic',
  'sonic-testnet',
  'taiko',
  'taiko-holesky-testnet',
  'unichain',
  'unichain-sepolia-testnet',
  'world',
  'world-sepolia-testnet',
  'x-layer',
  'x-layer-sepolia-testnet',
  'zircuit',
  'zircuit-sepolia-testnet',
];
