name: Check Markdown links

on: push

jobs:
  check-md-links:
    runs-on: ubuntu-latest
    steps:
    - name: Clone @api3/contracts
      uses: actions/checkout@v4
    - name: Check Markdown links
      uses: JustinBeckwith/linkinator-action@v1
