name: Continuous build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/contracts
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/contracts
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Verify vendor contracts
        run: pnpm verify-vendor-contracts

      - name: Test
        run: pnpm test
