name: Continuous build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/contracts
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - name: Build
        run: pnpm build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: pnpm test
